from collections.abc import Callable
from dataclasses import dataclass
from typing import Protocol

from app.domain.models import Board, Sound


@dataclass(frozen=True, slots=True)
class HotkeyCapability:
    available: bool
    message: str


class AudioEngine(Protocol):
    def play(self, sound: Sound, allow_overlap: bool) -> None: ...
    def stop(self, sound_id: int) -> None: ...
    def stop_all(self) -> None: ...


class BoardRepository(Protocol):
    def list_boards(self) -> list[Board]: ...
    def create_board(self, name: str) -> Board: ...
    def rename_board(self, board_id: int, name: str) -> Board: ...
    def delete_board(self, board_id: int) -> None: ...


class SoundRepository(Protocol):
    def list_sounds(self, board_id: int) -> list[Sound]: ...
    def get_sound(self, sound_id: int) -> Sound: ...
    def save_sound(self, sound: Sound) -> Sound: ...
    def delete_sound(self, sound_id: int) -> None: ...
    def has_source_path(self, source_path: str) -> bool: ...


class SettingsRepository(Protocol):
    def get_setting(self, key: str, default: str) -> str: ...
    def set_setting(self, key: str, value: str) -> None: ...


class HotkeyService(Protocol):
    def capability(self) -> HotkeyCapability: ...
    def register(self, hotkey: str, callback: Callable[[], None]) -> bool: ...
    def unregister(self, hotkey: str) -> None: ...
